import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Search from "./Search";

const inter = Inter({
  variable: "--font-inter",
  subsets: ["latin"],
  display: "swap",
});

export const metadata: Metadata = {
  title: "Next - Client",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={`${inter.variable} relative antialiased min-h-screen`}>
        <div className="container">
          {children}
          <Search />
        </div>
      </body>
    </html>
  );
}
